### ISSUE TITLE
$ifNull operator's replacement expression is false.

### ISSUE THREAD

**Issue by DavidKrpt** [aliatech/loopback-mongo-aggregate-mixin#8]
Hello and thanks for the package! I've been looking for a mixin like this and this is the best one yet.
After using it for a while, I found a few issues. I'll open separate threads for each one, if that's ok.

in lib/aggregation.js the coalesce method returns an $ifNull operator, where the replacement value is 'false' by default and there seems to be no way to overwrite it. When matching a relation field of type boolean to 'false' I'm getting nulls as positive matches.
<pre>
  coalesce (fields, coalesce = false) {
    const addFields = _.mapValues(fields, (value, key) => {
      return {$ifNull: [`$${key}`, coalesce]};
    });
    return this.append({
      $addFields: addFields,
    });
  }
</pre>

**Comment by Akeri** [comment]
Hi David, thank you for using this module and taking your time reporting issues.
I would like to be able to review it calmly and fix them. Meanwhile feel free to send PR if you find a solution. Thank you!

**Comment by DavidKrpt** [comment]
Thanks for replying.
Setting the default replacement value to "null" instead of "false" works for my purposes, but I don't know if it'll fit everyone's needs. Making it a fourth parameter for the .aggregate method doesn't seem like a clean solution either.
The other 2 issues I posted are even trickier, I'll let you know if I make any progress.

**Comment by Akeri** [comment]
Fixed with PR #11 by @DavidKrpt 
Thanks David!
